config/routes.rb
Rails.application.routes.draw do

   resources :payers

  # resources :pay_its

  resources :ut_students

  resources :coupons

  get 'events/search' => 'events#search'

  resources :reports

  mount Ckeditor::Engine => '/ckeditor'
  resources :answers

  resources :surveys

  resources :worldcups

  resources :price_models

  # get 'otherr_fail'=>'payments#other_fail',:as=>:payer_fail
  # get 'otherr_suc'=>'payments#other_suc',:as=>:payer_success

  get 'validate_ut/:token'=>'ut_students#validate_token',:as=>:validate_ut_email

  get 'payments/approve' => 'payments#approve'
  get 'payments/manual_new' => 'payments#manual_new'
  post 'payments/manual_new' => 'payments#manual_create'
  put 'payments/manual_approve/:id' => 'payments#manual_approve'
  resources :payments

  get 'participations' => 'events#participation_index'
  post 'participations/buy/:id' => 'events#manual_buy'

  get  'participations/new' => 'events#participation_new'
  post 'participations/create' => 'events#participation_create'
  delete 'participations/destroy/:id' => 'events#participation_destroy'

  # get 'new_payit'=>'payments#new_other_site'
  # get 'bank_payit/:payit_id'=>'payments#create_other_site', :as=>:bank_payit
  # get 'approve_payit/:payit_id' => 'payments#approve_other_site', :as=>:approve_payit


  resources :invoices

  resources :officerships

  #get 'events/index'
  #
  #get 'events/show'
  #
  #get 'events/new'
  #
  #get 'events/edit'

  get 'category/:category' => 'events#filter_by_category'
  get 'year/:year' => 'events#filter_by_year' , :as => :filter_by_year

  match 'user_import/import_users' ,to: 'user_import#import_users' ,via: :post

  get 'admin' => 'events#admin_index'

  root 'events#index'

  get 'coupons_by_price_model/:price_model_id', to: 'coupons#filter_by_price'

  devise_for :users, path: 'auth', path_names: {sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new'}, :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  # get 'live'=>'live#choose' => :as=>:live_choose

  get 'events/prebuy/:event' => 'events#prebuy', :as => :prebuy
  post 'buy' => 'events#buy', :as => :buy
  match 'temp_start_all' => 'events#temp_start_all', :as => :temp_start_all, :via => :get
  resources :events do
    member do
      resources :class_sessions
      match 'book' => 'events#book', :as => :book, :via => :post
      match 'book_conference' => 'events#book_conference',:as=>:book_conference, :via => :post
      match 'cancel' => 'events#cancel_book', :as => :cancel_book, :via => :delete
      match 'cancel_conference' => 'events#cancel_book_conference', :as => :cancel_book_conference, :via => :delete
      match 'start_register' => 'events#start_register', :as => :start_register, :via => :get
      match 'check_token/:token'=>'events#check_token', :as=>:check_token,:via=>:get
      match 'payed_participations'=>'events#payed_participations', :as=>:payed_participations,:via=>:get
      match 'live'=>'events#live',:via=>:get
    end
  end
  resources :profiles
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  acts_as_taggable
  include Authority::Abilities
  resourcify

  # associations
  has_many :participations
  has_many :participants, :through => :participations, :source => :profile
  has_many :subscriptions
  has_many :subscribers, :through => :subscriptions, :source => :profile
  has_many :officerships
  has_many :officers, :through => :officerships, :source => :profile
  has_many :class_sessions
  has_one :survey
  has_one :report
  has_many :price_models

  # attachments
  has_attached_file :poster, styles: {thumb: "x150"}
  
  # validations
  validates_attachment :poster, :content_type => { :content_type => ["image/jpeg", "image/png"] }, :size => { :in => 0..5.megabytes }
  
  def authors
    result = ""
    self.officers.each_with_index do |officer, i|
      result += (i == 0 ? "" : ", ") + officer.credentials
    end
    result
  end

  def members
    Profile.joins(:participations).merge(Participation.where("event_id = ?",self.id).where("payed = ?", true))
  end

  def members_mails
    s = ""
    Profile.joins(:participations).merge(Participation.where("event_id = ?",self.id).where("payed = ?", true)).each do |p|
      s += p.user.email + ";"
    end
    return s
  end

  #def registered_participants
  #  Profile.
  #end


  def can_register?
    Time.now < self.begins
  end

  def is_full?
    if self.price_models.size>0
      cap=PriceModel.where(:event=>self).sum(:capacity)
    else
      cap=self.capacity
    end
    cap <= participations.where('payed = ?',true).count
  end

end

app/controllers/events_controller.rb
#!/usr/bin/env ruby
# encoding: utf-8
class EventsController < ApplicationController
  before_action :authenticate_user!, :only => [:book, :cancel_book, :edit, :new]
  before_action :complete_profile
  before_action :set_event, :only => [:book_conference,:cancel_book_conference, :book, :cancel_book, :edit, :update, :show, :destroy, :start_register,:check_token,:payed_participations,:live]
  before_action :authenticate_live, :only => [:live]

  before_action :http_basic_authenticate,:only=>:check_token

  before_action :keep_notice

  before_action :authenticate_admin,:only=>[:payed_participations]

  def authenticate_live
    redirect_to events_path if !(current_user and current_user.participations.where(:payed=>true).map{|p|p.event.id}.include?(@event.id))
  end

  def authenticate_admin
    redirect_to events_path if !(current_user and current_user.has_role?(:admin))
  end

  def keep_notice
    flash.keep(:notice)
  end

  def http_basic_authenticate
    authenticate_or_request_with_http_basic do |name, password|
      name == 'feri' && password == 'khatar'
    end
  end

  def payed_participations
    @pars=Participation.where(:event=>@event,:payed=>true)
  end

  def index
    #@events = Event.all
    render 'events/choser', layout: false
  end 

  def admin_index
    if current_user and current_user.has_role?("admin")
      @events = Event.all
      render 'events/admin/admin_index'
    else
      redirect_to events_path
    end
  end

  def filter_by_category
    category = params[:category]
    if category == 'Class' or category == 'Ring' or category == 'Lab' or category == 'Workshop' or category=='Conference' or category=='Talk' or category=='Product'
      @events = Event.where("category = ?", category).where("begins > ?", Time.now).order(:begins)
      @archives = Event.where("category = ?", category).where("begins < ?", Time.now).order(:begins)
      @title = "رویدادها"
      if category == 'Class'
        @title = "کلاس‌ها"
      elsif category == 'Ring'
        @title = "حلقه‌ها"
      elsif category == 'Lab'
        @title = "آزمایشگاه و کارآموزی"
      elsif category == 'Workshop'
        @title = "ورک‌شاپ‌ها"
      elsif category == 'Conference'
        @title = "همایش ها"
      elsif category == 'Talk'
        @title = 'تاک ها'
      elsif category == 'Product'
        @title = 'محصولات قابل خرید'
      end
      render 'events/index'
    else
      redirect_to events_path
    end
  end

  def filter_by_year
    year = params[:year]
    all=Event.where("begins >= ?",Parsi::Date.new(year.to_i,1,1).to_gregorian()).where("begins <= ?",Parsi::Date.new(year.to_i+1,1,1).to_gregorian())
    @events=all.where("begins > ?", Time.now).order(:begins)
    @archives=all.where("begins < ?", Time.now).order(:begins)
    @title = 'تمامی رویدادهای سال '+year.to_s
    render 'events/index'
  end

  def show
    # authorize_action_for @event
  end

  def new
    @event = Event.new
    authorize_action_for @event
  end

  def create
    @event = Event.new(event_params)
    authorize_action_for @event
    if @event.save
      redirect_to root_path
    else
      render action: 'new', :alert => 'data validation failed.'
    end
  end

  def edit

  end

  def update
    authorize_action_for @event
    respond_to do |format|
      if @event.update(event_params)
        format.html {
          redirect_to events_path, notice: 'Event was successfully updated.'
        }
        #format.json { render :show, status: :ok, location: @cloth_part }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize_action_for @event
    @event.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Officership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def prebuy
    authenticate_user!
    @profile = current_user.profile
    @participation = Participation.where("profile_id = ?",@profile.id).where("event_id = ?",params[:event]).first
    @event = Event.find(params[:event])
    if @participation.profile != current_user.profile or Time.now > @event.begins
      redirect_to events_path
      return
    end
    if @participation.payed
      if @participation.event.category=="Product"
            send_file(
      @participation.event.product_address,
        :filename => @participation.event.product_address.split('/').last)
      else
      render 'events/successbuy'
    end
    elsif @participation.check_credit
      render 'events/errorbuy'
    else
      render 'events/prebuy'
    end
  end

  def live
    @address=""
  end

  def check_token
    par=Participation.where(:event=>@event,:enroll_token=>params[:token],:enroll_seen=>[nil,false]).first
    Rails.logger.info ":::::::::::::::::::::::::::::::::#{par} #{params[:token]} #{@event}"
    @pass=par
    if par
      par.update(:enroll_seen=>true)
      Rails.logger.info "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"
      render :text=>"SUCCESS"
    else
      Rails.logger.info "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
      render :text=>"FAILED"
    end
  end


  def buy
    authenticate_user!
    @profile = current_user.profile
    @participation = Participation.find(params[:participation])
    if @participation.profile != current_user.profile
      redirect_to @profile
      return
    end
    if @participation.payed
      if @participation.event.category=="Product"
            send_file(
      @participation.event.product_address,
        :filename => @participation.event.product_address.split('/').last)
      else
      render 'events/successbuy'
    end
    elsif @participation.check_credit
      render 'events/errorbuy'
    else
      if @participation.buy(@profile)
        if @participation.event.category=="Product"
            send_file(
      @participation.event.product_address,
        :filename => @participation.event.product_address.split('/').last)
      else
        render 'events/successbuy'
      end
      else
        redirect_to @participation.event, :notice => "فرآیند خرید با اشکال روبه‌رو شد."
      end
    end
  end


  def participation_index
    authenticate_user!
    #TODO
    if !current_user.has_role?(:admin)
      redirect_to events_path
      return
    end
    @participations = Participation.all
    render 'events/participation_index'
  end

  def participation_new
    #puts "AA"
    authenticate_user!
    #TODO
    if !current_user.has_role?(:admin)
      redirect_to events_path
      return
    end
    @participation = Participation.new
    puts "SS " + @participation.to_s
    render 'events/participation_new'
  end

  def participation_create
    puts "SSS"
    authenticate_user!
    #TODO
    if !current_user.has_role?(:admin)
      redirect_to events_path
      return
    end
    #puts participation_params
    #puts "AAAAAAAAAA"
    @participation = Participation.new(participation_params)
    @profile = @participation.profile
    if @participation.save
      if @participation.buy(@profile)
        redirect_to participation_index, :notice => "خرید این رویداد موفقیت‌آمیز بود"
      else
        # puts "::::::::::::::::::::::::::::",@participation.errors.messages
        redirect_to @participation.event, :notice => "فرآیند خرید با اشکال روبه‌رو شد."
      end
    end
  end

  def participation_destroy
    authenticate_user!
    #TODO
    if !current_user.has_role?(:admin)
      redirect_to events_path
      return
    end
    @participation = Participation.find(params[:id])
    @participation.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Participations was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def participation_params
    params.require(:participation).permit(:profile_id, :event_id)
  end

  def search
    if (params[:tags] || params[:name])
      @all=Event.tagged_with(params[:tags],:any=>true)
      @all=@all.where("title LIKE '#{params[:name]}' OR sentence LIKE '#{params[:name]}' OR description LIKE '#{params[:name]}' OR summary LIKE '#{params[:name]}'") if params[:name] && params[:name]!=""
      @events=@all.where("begins > ?", Time.now).order(:begins)
      @archives=@all.where("begins < ?", Time.now).order(:begins)
      render 'events/index'
    else
      render 'events/search'
    end
  end

  def manual_buy
    authenticate_user!
    #TODO
    if !current_user.has_role?(:admin)
      redirect_to events_path
      return
    end
    @participation = Participation.find(params[:id])
    @profile = @participation.profile
    if @participation.payed
      if @participation.event.category=="Product"
            send_file(
      @participation.event.product_address,
        :filename => @participation.event.product_address.split('/').last)
      else
      render 'events/successbuy'
    end
    elsif @participation.check_credit
      render 'events/errorbuy'
    else
      if @participation.buy(@profile)
        redirect_to participation_index, :notice => "خرید این رویداد موفقیت‌آمیز بود"
      else
        redirect_to @participation.event, :notice => "فرآیند خرید با اشکال روبه‌رو شد."
      end
    end
  end



  def start_register
    if current_user.has_role?(:admin)
      @event.participants.each do |p|
        UserMailer.start_register(p,@event).deliver
      end
      redirect_to admin_path, :notice => 'Send mails to ' + @event.title + ' participants'
      return
    end
    redirect_to events_path
  end

  def temp_start_all
    if current_user.has_role?(:admin)
      Profile.all.each do |p|
        UserMailer.send_all_register(p).deliver
      end
      redirect_to admin_path, :notice => 'Send mails to ' +' participants'
      return
    end
    redirect_to events_path
  end


  def book_conference
    authenticate_user!
    @profile = current_user.profile
    error=@profile.book_conference(@event,PriceModel.where(:id=>params[:price_model_id]).first,params[:cut_code])

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/admin/_admin_event_card.html.erb
<div class="event">

  <div class="column">
		<span class="feature date">
			<p class="day"><%= event.begins.strftime("%d") %></p>
			<p class="month"><%= event.begins.strftime("%B") %></p>
		</span>
    <!--<span class="feature audiences">-->
    <!--<i class="audience"></i>-->
    <!--<p class="info"><%= "#{event.participants.count} are going" %></p>-->
    <!--</span>-->
		<span class="feature register link" id="register<%= event.id %>">
			<% if current_user and event.participants.include? current_user.profile %>
                  <%= link_to cancel_book_event_path(event), :remote => true, :data => {:confirm => 'آیا مطمئن هستید که می‌خواهید لغو کنید؟'}, :method => :delete, :style => 'display: block' do %>
                    <i class="check"></i>
	    			<p class="info">
                      شرکت خواهم کرد! </p>
                  <% end %>
			<% elsif !event.is_full? %>

				<% if current_user %>
                    <%= link_to book_event_path(event), :method => :post, :style => 'display: block;', :remote => true do %>
                        <i class="link"></i>
                        <p class="info">
                          دوست دارید شرکت کنید؟ </p>
                    <% end %>
                <% else %>
                  <!--<a class="btn" id="login" data-toggle="modal" data-target="#main-modal">-->
                    <!--Log in to book!-->
                  <!--</a>-->

                  <%= link_to new_user_session_path, :method => :post, :style => 'display: block;' do %>
                        <i class="link"></i>
                        <p class="info">برای ثبت‌نام وارد شوید!</p>
                    <% end %>
                <% end %>
            <% else %>
                <i class=""></i>
				<p class="info">Full!</p>
			<% end %>
		</span>
        <span class="feature register link" id="register<%= event.id %>">
        <%= link_to "#", :style => 'display: block;' do %>
<p class="info">شرکت‌کنندگان</p>
              <p class="info"><%= event.participants.count %></p>
                    <% end %>
		</span>
        <span class="feature register link" id="register<%= event.id %>">
        <%= link_to edit_event_path(event), :style => 'display: block;' do %>
                        <i class="link"></i>
                        <p class="info">edit</p>
                    <% end %>
		</span>
        <span class="feature register link" id="register<%= event.id %>">
        <%= link_to event, :method => :delete, :style => 'display: block;', data: {confirm: 'Are you sure?'} do %>
            <i class="link"></i>
            <p class="info">remove</p>
        <% end %>
        </span>
        <span class="feature register link" id="register<%= event.id %>">
        <%= link_to new_class_session_path(event), :style => 'display: block;' do %>
            <i class="link"></i>
            <p class="info">New Class Session</p>
        <% end %>
        </span>
        <span class="feature register link" id="register<%= event.id %>">
        <%= link_to start_register_event_path(event), :style => 'display: block;', data: {confirm: 'Are you sure?'} do %>
            <i class="link"></i>
            <p class="info">Start Registeration</p>
        <% end %>
        </span>
  </div>
  <div class="content">
    <div class="wrapper">
      <div class="small-detail">
        <div class="title"><%= event.title %></div>
        <br>
        <% event.officerships.each do |o| %>
            <div class="authors">
              <%= o.profile.credentials %>
            </div>
            <div class="info">
              <p><%= o.description %></p>
            </div>
        <% end %>
      </div>
      <div class="big-detail">
        <div class="wrapper">
          <div class="poster-wrapper">
            <%= image_tag event.poster.url, :class => 'poster' %>
          </div>
          <div class="text-wrapper">
            <div class="sentence"><%= event.sentence %></div>
            <br>
          </div>
        </div>
        <div class="summary">
          <p class="info">شرکت‌کنندگان</p>

          <table class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Payed</th>
              <th>Date</th>
            </tr>
            </thead>

            <tbody>
            <% event.participants.each do |profile| %>
                <tr>
                  <td><%= link_to profile.credentials, profile %> </td>
                  <td><%= profile.user.email %> </td>
                  <td><%= (Participation.where("event_id = ?", event.id).where("profile_id = ?", profile.id).where("payed =?", true).count > 0).to_s %></td>
                  <% part = Participation.where("event_id = ?", event.id).where("profile_id = ?", profile.id).where("payed =?", true).last %>
                  <td>
                    <% if part != nil %>
                        <%= part.created_at %>
                    <% else %>
                        None
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :extra_js do %>
    <script type="text/javascript" lang="javascript">
        $(document).ready(function () {
            $('#login').click(function () {
                $.get('/users/sign_in', function (data) {
                    $('#main-modal-body').html(data);
                });
            });
        });
    </script>
<% end %>

app/views/events/admin/admin_index.html.erb
<div class="container">
  <div class="header">
    <div class="title">
      <%= @title %>
    </div>
    <div class="summary">
      <h4>
        شما می‌توانید با ثبت‌نام در سایت و شرکت در رویداد مورد نظر خود، از اخبار بعدی آن رویداد و هم‌چنین
        رویداد‌های جدید آگاه شوید. </h4>
      <span class="feature register link">
        <%= link_to new_event_path, :style => 'display: block;' do %>
                        <i class="link"></i>
                        <p class="info">new</p>
                    <% end %>
		</span>
      <!--<span class="feature register link">-->
        <!--<%= link_to temp_start_all_path, :style => 'display: block;', data:  {confirm: "Are you sure?"} do %>-->
                        <!--<i class="link"></i>-->
                        <!--<p class="info">Send Payment start Message to all</p>-->
                    <!--<% end %>-->
		<!--</span>-->

    </div>
  </div>
  <% @events.each do |event| %>
      <%= render 'events/admin/admin_event_card', :event => event %>
  <% end %>
</div>