config/routes.rb
Rails.application.routes.draw do

   resources :payers

  # resources :pay_its

  resources :ut_students

  resources :coupons

  get 'events/search' => 'events#search'

  resources :reports

  mount Ckeditor::Engine => '/ckeditor'
  resources :answers

  resources :surveys

  resources :worldcups

  resources :price_models

  # get 'otherr_fail'=>'payments#other_fail',:as=>:payer_fail
  # get 'otherr_suc'=>'payments#other_suc',:as=>:payer_success

  get 'validate_ut/:token'=>'ut_students#validate_token',:as=>:validate_ut_email

  get 'payments/approve' => 'payments#approve'
  get 'payments/manual_new' => 'payments#manual_new'
  post 'payments/manual_new' => 'payments#manual_create'
  put 'payments/manual_approve/:id' => 'payments#manual_approve'
  resources :payments

  get 'participations' => 'events#participation_index'
  post 'participations/buy/:id' => 'events#manual_buy'

  get  'participations/new' => 'events#participation_new'
  post 'participations/create' => 'events#participation_create'
  delete 'participations/destroy/:id' => 'events#participation_destroy'

  # get 'new_payit'=>'payments#new_other_site'
  # get 'bank_payit/:payit_id'=>'payments#create_other_site', :as=>:bank_payit
  # get 'approve_payit/:payit_id' => 'payments#approve_other_site', :as=>:approve_payit


  resources :invoices

  resources :officerships

  #get 'events/index'
  #
  #get 'events/show'
  #
  #get 'events/new'
  #
  #get 'events/edit'

  get 'category/:category' => 'events#filter_by_category'
  get 'year/:year' => 'events#filter_by_year' , :as => :filter_by_year

  match 'user_import/import_users' ,to: 'user_import#import_users' ,via: :post

  get 'admin' => 'events#admin_index'

  root 'events#index'

  get 'coupons_by_price_model/:price_model_id', to: 'coupons#filter_by_price'

  devise_for :users, path: 'auth', path_names: {sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new'}, :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  # get 'live'=>'live#choose' => :as=>:live_choose

  get 'events/prebuy/:event' => 'events#prebuy', :as => :prebuy
  post 'buy' => 'events#buy', :as => :buy
  match 'temp_start_all' => 'events#temp_start_all', :as => :temp_start_all, :via => :get
  resources :events do
    member do
      resources :class_sessions
      match 'book' => 'events#book', :as => :book, :via => :post
      match 'book_conference' => 'events#book_conference',:as=>:book_conference, :via => :post
      match 'cancel' => 'events#cancel_book', :as => :cancel_book, :via => :delete
      match 'cancel_conference' => 'events#cancel_book_conference', :as => :cancel_book_conference, :via => :delete
      match 'start_register' => 'events#start_register', :as => :start_register, :via => :get
      match 'check_token/:token'=>'events#check_token', :as=>:check_token,:via=>:get
      match 'payed_participations'=>'events#payed_participations', :as=>:payed_participations,:via=>:get
      match 'live'=>'events#live',:via=>:get
    end
  end
  resources :profiles
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :profile
  belongs_to :survey
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:integer)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>Integer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.integer %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Integer:</strong>
  <%= @answer.integer %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>