config/routes.rb
Rails.application.routes.draw do

   resources :payers

  # resources :pay_its

  resources :ut_students

  resources :coupons

  get 'events/search' => 'events#search'

  resources :reports

  mount Ckeditor::Engine => '/ckeditor'
  resources :answers

  resources :surveys

  resources :worldcups

  resources :price_models

  # get 'otherr_fail'=>'payments#other_fail',:as=>:payer_fail
  # get 'otherr_suc'=>'payments#other_suc',:as=>:payer_success

  get 'validate_ut/:token'=>'ut_students#validate_token',:as=>:validate_ut_email

  get 'payments/approve' => 'payments#approve'
  get 'payments/manual_new' => 'payments#manual_new'
  post 'payments/manual_new' => 'payments#manual_create'
  put 'payments/manual_approve/:id' => 'payments#manual_approve'
  resources :payments

  get 'participations' => 'events#participation_index'
  post 'participations/buy/:id' => 'events#manual_buy'

  get  'participations/new' => 'events#participation_new'
  post 'participations/create' => 'events#participation_create'
  delete 'participations/destroy/:id' => 'events#participation_destroy'

  # get 'new_payit'=>'payments#new_other_site'
  # get 'bank_payit/:payit_id'=>'payments#create_other_site', :as=>:bank_payit
  # get 'approve_payit/:payit_id' => 'payments#approve_other_site', :as=>:approve_payit


  resources :invoices

  resources :officerships

  #get 'events/index'
  #
  #get 'events/show'
  #
  #get 'events/new'
  #
  #get 'events/edit'

  get 'category/:category' => 'events#filter_by_category'
  get 'year/:year' => 'events#filter_by_year' , :as => :filter_by_year

  match 'user_import/import_users' ,to: 'user_import#import_users' ,via: :post

  get 'admin' => 'events#admin_index'

  root 'events#index'

  get 'coupons_by_price_model/:price_model_id', to: 'coupons#filter_by_price'

  devise_for :users, path: 'auth', path_names: {sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new'}, :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  # get 'live'=>'live#choose' => :as=>:live_choose

  get 'events/prebuy/:event' => 'events#prebuy', :as => :prebuy
  post 'buy' => 'events#buy', :as => :buy
  match 'temp_start_all' => 'events#temp_start_all', :as => :temp_start_all, :via => :get
  resources :events do
    member do
      resources :class_sessions
      match 'book' => 'events#book', :as => :book, :via => :post
      match 'book_conference' => 'events#book_conference',:as=>:book_conference, :via => :post
      match 'cancel' => 'events#cancel_book', :as => :cancel_book, :via => :delete
      match 'cancel_conference' => 'events#cancel_book_conference', :as => :cancel_book_conference, :via => :delete
      match 'start_register' => 'events#start_register', :as => :start_register, :via => :get
      match 'check_token/:token'=>'events#check_token', :as=>:check_token,:via=>:get
      match 'payed_participations'=>'events#payed_participations', :as=>:payed_participations,:via=>:get
      match 'live'=>'events#live',:via=>:get
    end
  end
  resources :profiles
  
end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :event
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  #before_action :authenticate_user!, :only => [:index, :new, :edit]
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      event=Event.where(:id=>params[:event])[0]
      event.report=@report
      if @report.save && event.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      # params.require(:event).permit(:title, :sentence, :description, :summary, :begins, :venue, :category, :capacity, :price, :poster, :officer_ids => [])
      params.require(:report).permit(:body,:event)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <%= f.cktext_area :body, :class => 'someclass', :ckeditor => {:language => 'fa'} %>

   <% event_id_map=[] %>
   <% Event.all.each do |e| %>
      <% event_id_map<<[e.title,e.id]%>
   <%end%>

   <%=select_tag(:event,options_for_select(event_id_map)) %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<%= report.event.title %>
<br>
<%=raw report.body%>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

    <% @reports.each do |report| %>
        <%= render 'reports/report', report: report %>
      
    <% end %>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>
<%= raw @report.body %>
<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>